### ISSUE TITLE
<Task> Create Barrel entity

### ISSUE THREAD

**Issue by krista-b** [UQdeco2800/2021-studio-2#100]
# **Description**
**Task:** Crate Entity
**Feature:** [Player Health Regeneration](#85)
create new class for a crate entity which is a destroyable obstacle. On destruction it spawns health potions that the player can walk over and regen health. Animations could also be added to the crate when hit and destroyed.

 
## **Example (optional)**

# **Dependencies**
- [x]  #101
- [x]  #99
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] add a create Barrel entity to obstacleFactory
- [x] Documentation for new Barrel entity in obstacleFactory
- [x] Create/add relevant components
- [x] Create animations with event handlers
 
**Completion Deadline:** Sep 13.
# **Documentation**
