### ISSUE TITLE
<Task> Have player health improve when potion collected

### ISSUE THREAD

**Issue by krista-b** [UQdeco2800/2021-studio-2#104]
# **Description**
**Task:** Health regen after collecting potion
**Feature:** [Player Health Regeneration](#85)
Give the player its hp back after taking a pot.

## **Example (optional)**

# **Dependencies**
- [x]  #102
- [x] #103
- [ ] #129
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] event handler for when player walks over potion
- [x] tell player to give itself hp
- [x] delete the potion entity from game
 
**Completion Deadline:** Sep 13.
# **Documentation**
