### ISSUE TITLE
<Task> Randomised Dialogue

### ISSUE THREAD

**Issue by Jonoym** [UQdeco2800/2021-studio-2#105]
This ticket is a part of Feature #84, Dialogue and Cutscenes extension

# Randomised Dialogue

The player over many runs will encounter the same bosses many times. To make this more interesting, dialogue should be diverse and possibly dependent on whether the boss has killed the character before, or the boss has been killed.

## Tasks

- [x] Create a set of unique dialogue that relates to the bosses interacting with the character (5th August)
- [x] Create dialogue based on having already defeated the boss (6th August)
- [x] Create dialogue based on being defeated the boss previously (6th August)

### Dependencies
Dialogue that occurs once a boss has been defeated will be dependent on how the game will track if the boss has been defeated, currently there are no bosses and no way of killing enemies so this feature will be transferred over once they are added.

**Completion Deadline:**  September 7th .
 
# **Documentation**
[Cutscenes](Cutscenes)

# **Members**
- Jonathan Tang (@Jonoym)(Jonoym#0974)
