### ISSUE TITLE
<Task> Dialogue Display

### ISSUE THREAD

**Issue by Jonoym** [UQdeco2800/2021-studio-2#107]
This ticket is a part of Feature #84, Dialogue and Cutscenes extension

# Dialogue Display

The display of the text box is currently a placeholder and will need to be scaled up in a pixelated art style. The design of the character should maintain its pixelated art style.

## Tasks

- [x] Create a general art style guide for the text boxes
- [x] Create text boxes that relate to the current map of the game
- [x] Create scaled up versions of the main character and NPCs 

### Dependencies
Dialogue that occurs once a boss has been defeated will be dependent on how the game will track if the boss has been defeated, currently there are no bosses and no way of killing enemies so this feature will be transferred over once they are added.

**Completion Deadline:**  September 7th .
 
# **Documentation**
[Cutscenes](Cutscenes)
[Text Box Display](Text-Box-Display)

# **Members**
- Jonathan Tang (@Jonoym)(Jonoym#0974)
