### ISSUE TITLE
<Task> Tutorial Room

### ISSUE THREAD

**Issue by Jonoym** [UQdeco2800/2021-studio-2#108]
This ticket is a part of Feature #84, Dialogue and Cutscenes extension

# Tutorial Room

The tutorial will be a section of the game that will be shown on first play as well as an option to return to. Ideally, it should provide a basis of the overall story line as well as providing controls and tips to the player.

## General Ideas

The tutorial should guide the main character through the starting place (dungeon/jail), getting the player to practice moving to certain areas to explain the next part of the tutorial. Practicing attacks could be done on a training dummy as well an abilities. 

## Tasks

- [x] Create a set of dialogue that will explain the controls of the game 
- [x] Include the storyline of the game in the dialogue as well as design of the tutorial
- [ ] Tutorial can be quit easily and will proceed to the main game
- [x] Alternates between controls and getting the player to practice

### Dependencies
The tutorial will be dependent on the map since the main character should not be in any danger, there can be NPC enemies that do no damage but killing them will proceed with the tutorial.

**Completion Deadline:**  September 7th .
 
# **Documentation**
[Cutscenes](Cutscenes)
[Text Box Display](Text-Box-Display)

# **Members**
- Jonathan Tang (@Jonoym)(Jonoym#0974)

**Comment by Jonoym** [comment]
There is no main game that the tutorial precedes so it is not yet possible to quit out of the tutorial to quickly move on to the main game.
