### ISSUE TITLE
<Task> Map Asset Ideation and Design

### ISSUE THREAD

**Issue by ameliarow** [UQdeco2800/2021-studio-2#109]
This ticket is a part of Feature #84, Asset Design Work extension

# Map Asset Ideation and Design

Begin ideating and designing assets for the maps, including obstacles, tiles and/or other scene items. 
 
## **Milestones**
List of steps that need to be completed for this task.
- [x] Create a general art style for map assets. (TBD)
- [x] Create multiple design prototypes and potential ideations of map assets. (TBD)
- [x] Begin refining/iterating designs. (TBD)
 
### Dependencies
Asset Art and Map Design Style: the designs will be dependent on the overall art style of the game and will be closely related and based on this.

**Completion Deadline:** September 13.
 
# **Documentation**
- [Map Design](https://github.com/UQdeco2800/2021-studio-2/wiki/Map-Design)
- ...
 
# **Members**
- Amelia Rowhani (@ameliarow) (#ameliaro #6002)
