### ISSUE TITLE
<Task> Camera Tracking

### ISSUE THREAD

**Issue by GreyAtlantean** [UQdeco2800/2021-studio-2#11]
# Camera 

From Feature Ticket #4, Player Design, Movement and Camera Tracking

The purpose of this ticket is to get the camera to track the player keeping them in the center of the screen and only stopping that once the player reaches the edge of the room at which point the camera will stop at just beyond the edges of the room. 

Dynamically changing camera zooms has been suggested and would potentially make the game more interesting and immersive  but could also feel out of place. This suggestion has been added as an extra component that could be tested and added but it is not required. 

### Milestones

- [x] Have the camera set up
- [x] Settle on a suitable zoom level 
- [x] Have the camera keep the player centered 
- [ ] Have the camera 'unlock' and not keep the player centered once the edge of the room gets too much into view

### Extras

- [ ] Dynamically changing camera zooms based on room size and enemy distances.

## Documentation
[Camera Tracking](Camera-Tracking)

**Comment by Jonoym** [comment]
Having the camera stop moving is very reliant on how the map is generated and the walls. Could not implement and test if it would work with a proper map layout since it has not been implemented yet.
