### ISSUE TITLE
<Task> Asset Design Evaluation/Refinement

### ISSUE THREAD

**Issue by ameliarow** [UQdeco2800/2021-studio-2#110]
This ticket is a part of Feature #84, Asset Design Work extension

# Asset Design Evaluation/Refinement

Begin evaluating and refining the map asset designs as well as testing the main character design to better align with the game style and theme.
 
## **Milestones**
List of steps that need to be completed for this task.
- [x] Begin user testing of the map asset/character design. (TBD)
- [x] Evaluate potential refinements to colour, shading or pixel art style. (TBD)
- [x] Begin refining initial designs. (TBD)

**Completion Deadline:** September 13.
 
# **Documentation**
- [Main Character](https://github.com/UQdeco2800/2021-studio-2/wiki/Main-Character)
- ...
 
# **Members**
- Amelia Rowhani (@ameliarow) (#ameliaro #6002)
