### ISSUE TITLE
<Task> Iteratively design the text box to associate the style of different scenes

### ISSUE THREAD

**Issue by Carloslyx** [UQdeco2800/2021-studio-2#113]
# Iteratively design the text box
The test box should display different images according to different characters and different maps, so more and different style versions are needed.

## General Ideas
Characters, enemies, and bosses need to have a dedicated Test Box. And the style of the box needs to be designed according to the style of different maps.

## Task

- [x] Making enemies of test box
- [x] Make the test box of the boss
- [x] Make a prison map style text box

# Dependencies
This needs to be based on the image design of the enemy and the boss and different map design styles.

# Documentaion
# Members

- Carlos Liu (@Carloslyx) (Carlos Liu#6008)
