### ISSUE TITLE
<Feature> Saving and Loading

### ISSUE THREAD

**Issue by GreyAtlantean** [UQdeco2800/2021-studio-2#114]
# Saving and Loading
Implement a way to save and track what the player has done in the game
 
## **Milestones**
List of steps that need to be completed for this task.
- [x] Design a save format for the game (6 Sep)
- [x] Setup reading and writing the save file (20 Sep)
- [x] Implement a way to update save file (21 Sep)
- [x] Implement a way to get events that occur and change save file based on them (25 Sep)
- [x] Setup ability to load save file (26 Sep)

**Completion Deadline:** 28th Sep.
 
# **Documentation**
- 
- ...
 
# **Members**
Muhammad Pathan (@GreyAtlantean ) (#GreyAtlantean 0010)

**Comment by Jonoym** [comment]
Will be revisited next sprint.

**Comment by Jonoym** [comment]
Since the maps and bosses have not been added to the game as of now, this ticket will be closed since all of the functionality is already there and adjustments for when the save is made will be carried out once the they are in the game.
