### ISSUE TITLE
<Feature> Improved Attack Mechanics

### ISSUE THREAD

**Issue by jac0be** [UQdeco2800/2021-studio-2#115]
# **Description**
The basic character attack needs to be improved. This includes but not limited to improved animations, more attacks for each weapon as well as new weapons with different attack functionality and design.
 
## **Examples**
* Axe (Starting Weapon)
* Thor's Hammer (Mjolnir)
* Loki's spear (Laevitan)
* Heimdall's longsword (Hofund)
* Ullr's bow (Tyrfing)

# **Dependencies**
None

# **Milestones**
- [x] Improve base melee weapon functionality, including hit-boxes, knockback, and health reduction
- [x] Make every weapon both a primary, and secondary attack.
- [x] #116
- [x] Make Thor's hammer (Mjolnir)
- [x] Make Loki's spear (Laevitan)
- [x] Make walking animations with equipped weapons.
 
**Completion Deadline:** Sep.14
 
# **Extras**
- [ ] Heimdall's Longsword (Hofund)
- [ ] Ullr's Bow (Tyrfing)
 
# **Documentation**
- [MeleeWeapon](../wiki/Melee-Weapons)
- [WeaponHitboxComponent](../wiki/WeaponHitboxComponent)
 
# **Members**
- Martin Baer (@martinrbaer ) (Marty#7869)
- Jacob Edwards (@jac0be) (chrised#1330)
- Yilin Su (@suylyus) (Yilin #2263)
- Jiaao Chu (@JiaaoChu) (ChildeWhite#7324)
- Sabrina Menezes (@sabrinaleah) (bree#3373)
