### ISSUE TITLE
<Task> Improve Axe

### ISSUE THREAD

**Issue by jac0be** [UQdeco2800/2021-studio-2#116]
Improve Axe design, animations, and mechanics. Add smear frames to communicate motion, also modify hit-box creation and destruction to match animation. Also modify axe attack to feel better.

# **Dependencies**
None 

**Completion Deadline:** 
Sep. 7

# **Documentation**
- [Main description of feature](../../wikis/page1)
- [JavaDoc](JavaDoc/Location/Package/Class)

# **Milestones**
- [x] Improve axe animations
- [x] Improve axe attack functionality
- [x] Implement axe AOE attack functionality
- [x] Design axe AOE attack animation

# **Member**
- Jacob Edwards (@jac0be, #chrised1330)
