### ISSUE TITLE
<Task> New Projectile Types

### ISSUE THREAD

**Issue by eco9898** [UQdeco2800/2021-studio-2#122]
# **Description**
**Task:** New Arrow Types
**Feature:** [Team 2 - Minion combat and Boss fights](96) 
 
- [x] Slow heavy-hitting tracking fireball (Restrict turning angles to smooth out following)
- [x] Fast low damage arrow
- [x] Hitscan sniper arrow
- [x] implement fireball animation
- [x] implement heads up animation on hitscan arrow
- [x] Fireballs will hover over the enemy until ready to be fired

**Completion Deadline:** Sep. 5

# **Member**
- Eli (@eco9898 ) (.♡.𝓮𝓵𝓲.♡.#5723)

**Comment by eco9898** [comment]
Features implemented, just need new animation and sprites for the hitscan and fireballs
