### ISSUE TITLE
<Task> Weapon class (character attack)

### ISSUE THREAD

**Issue by jac0be** [UQdeco2800/2021-studio-2#13]
Define and sketch weapon inheritance structure using class diagrams, create abstract weapon class, and implement basic functionality common to all weapons. 

# **Dependencies**
- None

**Completion Deadline:** Aug. 22
 
# **Documentation**
- [Main description of feature](../../wikis/page1)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...

# **Milestones**
- [x] Create class diagram and upload to wiki
- [x] Create abstract weapon class
- [x] Create abstract melee weapon class 

# **Member**
- Jacob Edwards
