### ISSUE TITLE
<Task> Scepter Attack 

### ISSUE THREAD

**Issue by suylyus** [UQdeco2800/2021-studio-2#130]
# **Description**
**Task:** [Scepter Attack].
**Feature:** [Feature which this tasks contributes to implementing]

Enable Character attack by a spear.
 
# **Dependencies**.

None
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Animation Draft (Sep. 5)
- [x] Design Light Attack Animation (Sep.7)
- [x] Design Strong Attack Animation  (Sep.9)
- [x] Implement Light Attack (Sep. 12)
- [x] Implement Strong Attack (Sep. 13)
 
# **Member**
- Martin Baer (@martinrbaer ) (Marty#7869)
- Yilin Su(@suylyus ) (Yilin #2263)
