### ISSUE TITLE
<Task> Make Mjolnir

### ISSUE THREAD

**Issue by jac0be** [UQdeco2800/2021-studio-2#136]
Make Thor's Hammer, Mjolnir. Light attack will be a melee attack similar to the Axe. Strong attack will be a ranged boomerang type attack, where the user throws and recalls it. Animations will make use of lightning type effects and aesthetics.

# **Dependencies**
None 

**Completion Deadline:** 
Sep. 14

# **Documentation**
- [Main description of feature](../../wikis/page1)
- [JavaDoc](JavaDoc/Location/Package/Class)

# **Milestones**
- [x] Make Mjolnir weapon model
- [x] Make Mjolnir animations
- [x] Make Mjolnir light attack functionality
- [x] Make Mjolnir strong attack functionality

# **Member**
- Jacob Edwards (@jac0be, chrised#1330)
- Sabrina Menezes (@sabrinaleah, bree#3373)
