### ISSUE TITLE
<Task> Story and Dialogue

### ISSUE THREAD

**Issue by GreyAtlantean** [UQdeco2800/2021-studio-2#14]
# Story and Dialogue

**Task:** Story and Dialogue
**Feature:** This ticket is a part of Feature #4, Camera Movement, Story, Player Design and Dialogue

## Story

This task will cover both coming up with the plot concept for the game and finalising the backstory and storyline so the game feels consistent and coherent to the player. The storyline will be used to define the major events within the game as well as provide insight to the motivation of the main character.

Ideally, we would like to finalise the story as early as possible since changing the storyline will be difficult once progress has been made. Feedback will be looked for from other project members and people outside of the project. 

## Milestones

- [x] Have the basic backstory for player character in place
- [x] Have the players progression through the story loosely figured out
- [x] Know what major characters the player will meet will be
- [x] Obtain feedback about the storyline and potential improvements

**Completion Deadline:** Aug 30.
 
# **Documentation**
- [Main description of feature](../../wikis/page1)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Members**
- Muhammad Pathan (@GreyAtlantean)(#Grey Atlantean#0010)
