### ISSUE TITLE
<Task> Importing of Traps from JSON

### ISSUE THREAD

**Issue by parker334** [UQdeco2800/2021-studio-2#146]
# Description
Import different types of traps form JSON file, including ones that can be walked over and one which are obstacles. These traps cover multiple tiles, and must be resizable.

# Milestones
- [x] Create Resizable Walkover Trap Object
- [x] Create Resizable Obstacle Trap Object
- [x] Importing of Lava Trap (Walkover) via JSON
- [x] Importing of Spike Trap (Obstacle) via JSON

**Completion Deadline:**
Sep. 11

# Member
- William Parker (@parker334) (parker334#2323)
