### ISSUE TITLE
<Task> Arrow and fireball death still needs to be implemented

### ISSUE THREAD

**Issue by eco9898** [UQdeco2800/2021-studio-2#175]
# **Description**
**Task:** Animate arrow/entity dying effect
**Feature:** [Team 2 - Minion combat and Boss fights](96) 
 
- [x] Create arrow break animation
- [x] Createfireball flameout animation
- [x] Trigger arrow break animation on death
- [x] Trigger fireball flameout animation on death

**Completion Deadline:** Sep. 18

# **Member**
- Minh Tieu (@MTbir) Minh#7523
- Haopeng Xia (@HaoPengXia) HaoPengXia(Barney)#8321

**Comment by eco9898** [comment]
Will be carried over to sprint 3

**Comment by MTbir** [comment]
Complete - trigger animation

**Comment by eco9898** [comment]
There is now an issue #228

**Comment by MTbir** [comment]
Update death animation teleport -> need to update the hitBox bound
