### ISSUE TITLE
[Feature] Team 2 - Minion combat and Boss fights part 2

### ISSUE THREAD

**Issue by eco9898** [UQdeco2800/2021-studio-2#181]
# Description 
This sprint we are finishing off sprint 2 and addressing bugs. We also need to add quality check our wiki, tests, and javadoc

#  Milestones 
## Design and animations: 
- [ ] #125
- [ ] Enemy sprites for sniper elves
- [ ] #126
- [ ] Remove hitbox over the bow as this shouldn't trigger damage
- [ ] #175
- [ ] #174
- [ ] #173

## Combat
- [ ] #123

## Attacks
- [ ] Use player like weapon system

## Stretch Goals: 
- [ ] Particle effect for fireballs
- [ ] Add new Boss attacks
  - [ ] Boss explosion knockback attack
  - [ ] New AI system at low health to make boss more rabid/raged
- [ ] Boss music when player approaches boss
- [ ] External melee weapon sprite like the player has

## Bug fixes
- [ ] #156 
- [ ] #172
- [ ] #160
- [ ] #159
- [ ] #158

# Members
- Fleur Nicholson (@FleurN21) Fleur#0608
- Minh Tieu (@MTbir) Minh#7523
- Eli Cox (@eco9898) .♡.𝓮𝓵𝓲.♡.#5723
- Kai Barry (@BobJohnsom) BOBJohnson#5476
- Haopeng Xia (@HaoPengXia) HaoPengXia(Barney)#8321
