### ISSUE TITLE
<Task> pause and unpause game

### ISSUE THREAD

**Issue by sadrabt** [UQdeco2800/2021-studio-2#192]
This task is part of feature #184 

### Description
Pause and unpause game using user input, this includes pausing all player and enemy movements, attacks, projectiles, and animations

### Milestones
- [x] Add pause function
- [x] pause game time
- [x] pause tasks in progress

### Members
Sadra Bayat Tork (@sadrabt) (@sadra#9931)
