### ISSUE TITLE
<Task> display pause menu

### ISSUE THREAD

**Issue by sadrabt** [UQdeco2800/2021-studio-2#193]
### Description
Menu with different options is displayed while the game is paused

### Milestones
- [x] Display menu background
- [x] Display Buttons
- [x] Implement button functionality
- [x] Implement resizing when window size is changed

### Members
Sadra Bayat Tork (@sadrabt) (@sadra#9931)
