### ISSUE TITLE
[Feature] Team 4 - Map Redesign and Integration

### ISSUE THREAD

**Issue by parker334** [UQdeco2800/2021-studio-2#197]
# Description 
Redesign map so instead of one big area, multiple smaller game areas are teleported between. Integrate other teams features into the current map and the Tiled.

# Milestones
- [x] #198
- [x] #199
- [x] Split Current Tiled Map into multiple Tiled maps
- [x] #266
- [x] #265
- [x] #267
- [x] #268
- [ ] Integration with other team enemies spawning
- [x] Integration with other team objects spawning
- [x] #219
- [x] #211
- [x] #220
- [x] Implement more thorough user testing
- [ ] Clean up redundant code in GameArea.
- [ ] Integrating other teams additions into map **More milestones will be added on this.**

# Dependencies
Team 

# Documentation
[Wiki](https://github.com/UQdeco2800/2021-studio-2/wiki)

# Members
Benjamin Gonzalez (@BenjaminGonzalez) (Benjamin-Gonzalez-#2927)
Sicheng Pan (@GoldMan93) (GW.Goldman#8858)
William Parker (@parker334) (parker334#2323)
Nicolas Armstrong (@Nicolas-Armstrong) (FalconLuma#3614)
Quan Tran (@othiem) (Quan Tran#0165)

**Comment by BenjaminGonzalez** [comment]
The milestone of splitting maps into smaller individual levels has been completed and since it was a small task no task issue was added
