### ISSUE TITLE
[Feature] Team 1 - Cutscene Implementation and Story

### ISSUE THREAD

**Issue by Jonoym** [UQdeco2800/2021-studio-2#200]
# Cutscene Implementation

Since some maps have been implemented, the cutscene explaining the area, the God and the storyline will be needed to provided a coherent storyline. Each area will have a different map art style and the text box which corresponds to this area/boss should fit the theme.

## Tasks

- #206 
- #207
- #208 
- #209 
- #210 
- #212 
- #213

### General

- [x] Finalising the tutorial that includes the newly implemented controls and traps
- [x] Plan the cutscenes to be implemented and where they will be triggered
- [x] Create the dialogue behind the Elf boss and Loki for all types of interactions
- [ ] Creation of more NPCs along the map
- [ ] Adding more cinematic cutscenes to fill unused game time
- [x] Create text box displays that match the maps to be implemented
- [x] Cutscene on teleporting between areas

### Extras

- [x] Adding dialogue for the Odin and Thor bosses
- [ ] Dialogue implementation for the end game

## Dependencies

There are still ongoing changes to be made with the map as well as the generation of the enemies. With the implementation of a pause feature, it may be possible for the cutscenes to pause the AI of the enemies to prevent the player from being hurt.

Currently, the triggers are being hard coded into the game due to the various parameters that are required, this will depend on the map size which is still being finalised.

# Story

With all the changes to the story, the story needs to have a finalised direction that can be expanded on but should not be deviated from. The current storyline will have the player imprisoned by Loki, in Helheim. From here the player needs to escape the prison by defeating the Elf who overlooks the area.

After escaping, the player will now be in Helheim, with Loki as the boss that is required to be defeated to advance to the Asgard areas.

### General

- [x] Create the dialogue that clearly explains the storyline
- [ ] Create the NPCs that will deliver the dialogue, this can be done with random NPCs found around the map as well as direct dialogue between the player and boss
- [x] Randomisation of the dialogue on repeated attempts of the game

# **Members**
- Jonathan Tang (@Jonoym) (Jonoym#0974)

**Comment by Jonoym** [comment]
Implementing more NPCs into the map for the player to talk to will be looked into next sprint if there is time. Some reasons that it may not benefit the game is that it disjoints the gameplay which it shouldn't as the gameplay is the most important factor. 

The team that is designing the ending will cover the ending dialogue.
