### ISSUE TITLE
[Feature] Team 1 - Loki Boss Assets

### ISSUE THREAD

**Issue by Jonoym** [UQdeco2800/2021-studio-2#202]
# Loki Boss

Loki is one of the bosses planned to be implemented into the game, both as a boss and an NPC. To make the boss fight feel interesting, animations and a high quality design of the boss needs to be implemented.

## Tasks

- #203
- #204 
- #205

### General

- [x] Finalisation of the Loki character design
- [x] Idle frames for the four basic directions of movement
- [x] Walking animations for Loki
- [x] Implementing the weapon into the character art
- [x] Creating the attack animations with the specified weapon
- [ ] Design the projectile attack art
- [x] Death animation of Loki boss
- [x] User testing based focusing on coherency of the game, animations and overall visual of the NPC

### Extras

- [ ] Potentially help with the AI of the boss and attacks that would align well with the mythology of the character
- [x] Implementing a base minion with similar art assets

## Documentation

The set of dialogue for the NPCs can be found here along with the plan for when they will be player: [Dialogue](Dialogue)

## Dependencies

Loki NPC will be dependent on how the enemy team will implement the AI of the character. Ideally the character will have a strong personality shown throughout dialogue but more importantly attack gameplay. 

Since this feature is only focusing on the assets that correspond to Loki, this implementation of the final boss will be very dependent on the AI which will be done by the Enemies team.

# **Members**
- Jonathan Tang (@Jonoym) (Jonoym#0974)
