### ISSUE TITLE
[Task] Loki Base Frames

### ISSUE THREAD

**Issue by Jonoym** [UQdeco2800/2021-studio-2#203]
This ticket is a part of Feature #202 , Loki Boss Assets

# Loki Frames

Creation of the base model of the Loki NPC which will be built upon for animations.

## Tasks

- [x] Create the base design for the Loki NPC
- [x] Create the idle frames for the NPC in all four directions
- [x] Implementation of the weapon into the base frames
 
# **Documentation**

# **Members**
- Jonathan Tang (@Jonoym)(Jonoym#0974)

**Comment by Jonoym** [comment]
The Loki NPC frames have been updated to provide a more Norse aesthetic from the previous modern theme. The jacket has been changed to a green coat with decorations added. The frames also include the walking animation, death animation and attack animation, all using the Scepter weapon.
