### ISSUE TITLE
[Task] Loki Boss Animations

### ISSUE THREAD

**Issue by Jonoym** [UQdeco2800/2021-studio-2#204]
This ticket is a part of Feature #202 , Loki Boss Assets

# Loki Frames

The animations of Loki will make the character feel more realistic within the game, providing better boss fights visually. 

## Tasks

- [x] Walking animations for Loki NPC
- [x] Attacking animations for Loki NPC
- [x] Death animations for Loki NPC
 
# **Documentation**

# **Members**
- Jonathan Tang (@Jonoym)(Jonoym#0974)
