### ISSUE TITLE
[Task] Loki Attack Projectile Art

### ISSUE THREAD

**Issue by Jonoym** [UQdeco2800/2021-studio-2#205]
This ticket is a part of Feature #202 , Loki Boss Assets

# Loki Attacks

Creation of the base model of the Loki NPC which will be built upon for animations.

## Tasks

- [x] Decide the types of attacks that match the character well
- [x] Create potential designs for the attacks
- [ ] Create the projectile art that will be used by Loki
 
# **Documentation**

# **Members**
- Jonathan Tang (@Jonoym)(Jonoym#0974)

**Comment by Jonoym** [comment]
The Loki boss is currently reusing projectiles from the Elf boss. Due to lack of knowledge for the projectile types, animations and implementation, these may be looked at later when polishing the game as it is only a visual change. The change may be deferred to another team as well.
