### ISSUE TITLE
[Task] Dialogue for Bosses

### ISSUE THREAD

**Issue by Jonoym** [UQdeco2800/2021-studio-2#206]
This ticket is a part of Feature #200  , Cutscene Implementation and Story

# Boss Dialogue

Create a set of dialogue that relates well with the character's personality. The sets of dialogue should include the first encounter, encounters after a recent defeat by the boss or encounters after recently defeating the boss.

## Tasks

- [x] Dialogue for the Elf boss and and other dialogue within that map
- [x] Dialogue for the Odin boss and and other dialogue within that map
- [x] Dialogue for the Loki boss and and other dialogue within that map
- [x] Dialogue for the Thor boss and and other dialogue within that map
 
# **Documentation**

# **Members**
- Jonathan Tang (@Jonoym)(Jonoym#0974)
