### ISSUE TITLE
[Task] Tutorial Room and Dialogue

### ISSUE THREAD

**Issue by Jonoym** [UQdeco2800/2021-studio-2#207]
This ticket is a part of Feature #200  , Cutscene Implementation and Story

# Tutorial

The tutorial map should soon be implemented and with new feature within the game, the tutorial needs to be updated to account for them. The tutorial will be centred around a prisoner helping the player learn controls and the map design.

## Tasks

- [x] Update the dialogue for the tutorial to account for new features
- [x] Implement the NPC into the tutorial map
- [ ] Implement cutscenes and triggers within the map
- [ ] Features to allow for an easy escape from the tutorial
 
# **Documentation**

Plans for the dialogue to be implemented are shown here, this also the potential lines of dialogue within the game: [Dialogue](Dialogue)

# **Members**
- Jonathan Tang (@Jonoym)(Jonoym#0974)
