### ISSUE TITLE
[Task] More NPCs

### ISSUE THREAD

**Issue by Jonoym** [UQdeco2800/2021-studio-2#210]
This ticket is a part of Feature #200, Cutscene Implementation and Story

# More NPCs

The story will be conveyed mostly through dialogue, there should be breaks between gameplay to reveal more information about the story. These NPC interactions can be randomised based on previous meetings

## Tasks

- [x] Design NPCs that will be encountered in the map
- [x] Write the dialogue that will fit with the NPC
- [ ] Implement the NPC into the map
 
# **Documentation**

# **Members**
- Jonathan Tang (@Jonoym)(Jonoym#0974)

**Comment by Jonoym** [comment]
Since the map has not been pushed to main, it cannot be implemented into the map yet. The code and dialogue has already been prepared to be added so insertion into the game within the game area is all that will be required.
