### ISSUE TITLE
[Task] Paused NPC Task

### ISSUE THREAD

**Issue by Jonoym** [UQdeco2800/2021-studio-2#212]
This ticket is a part of Feature #200, Cutscene Implementation and Story

# Paused NPC Task

The player may be attacked by the NPCs during cutscenes or at the very start of the game. To prevent this, the NPC AI needs to include a paused task. This will help with the implementation of the pause menu as well as allowing cutscenes to feature enemies close to the player.

## Tasks

- [x] Add the idle task to the player to prevent them from moving
- [x] Increase the priority of the task depending on if the game has been paused
- [x] Pause the game when cutscenes are being played

## Dependencies

Team 3 will be working on the pause screen and are planning on ways to show the pause screen while hiding the actual game. Changing the task priority will be dependent on these changes but will be easily hooked up after implementation.

# **Documentation**

# **Members**
- Jonathan Tang (@Jonoym)(Jonoym#0974)
