### ISSUE TITLE
[Feature] Team 1 - Map Design Assets

### ISSUE THREAD

**Issue by ameliarow** [UQdeco2800/2021-studio-2#214]
# Map Design

Continuation, testing and refinement of map asset designs will be conducted to make the map rooms feel more realistic and better align with the game theme. A new outdoor map level will be designed to better suit the Norse game storyline. Map assets will be ideated and designed for both indoor and outdoor map levels, including potential obstacles, tiles and/or other scene items, as well as a more defined map colour scheme. 

## Tasks

- #215 
- #216 

### General

- [x] Begin design and ideation of obstacle assets for the outdoor map design
- [x] Iterate and create additional assets for the indoor map designs
- [x] Design tile assets
- [x] Design decoration tile assets
- [x] Conduct further user testing of the map asset designs
- [x] Begin user testing of each map level/room design
- [x] Refine the layout and tile placement for the map levels
- [x] Refine and iterate designs

## Dependencies

Map asset design will be dependent on the overall art style of each map room to ensure designs are consistent and align with the game theme. They will largely depend on progress made by the map team and will enhance current design work and implementation.

# **Members**
- Amelia Rowhani (@ameliarow ) (ameliaro#6002)
