### ISSUE TITLE
<Task> Indoor Map Asset Design

### ISSUE THREAD

**Issue by ameliarow** [UQdeco2800/2021-studio-2#215]
This ticket is a part of Feature #214, Map Design Assets

# Indoor Map Asset Design

Continue ideating and designing assets for the indoor map rooms, including obstacles, tiles and/or other scene items.

## Tasks
- [x] Create multiple design prototypes and potential ideations of indoor map assets. (TBD)
- [x] Refine art style for indoor map assets. (TBD)
- [x] Begin refining/iterating designs. (TBD)
- [x] Refine layout and overall defined design of each map room. (TBD)
 
### Dependencies
Asset Art and Map Design Style: the designs will be dependent on the overall art style of the game and will be closely related and based on this.
 
# **Documentation**
- [Map Design](https://github.com/UQdeco2800/2021-studio-2/wiki/Map-Design)
- ...
 
# **Members**
- Amelia Rowhani (@ameliarow) (#ameliaro #6002)
