### ISSUE TITLE
<Task> Outdoor Map Asset Design

### ISSUE THREAD

**Issue by ameliarow** [UQdeco2800/2021-studio-2#216]
This ticket is a part of Feature #214, Map Design Assets

# Outdoor Map Asset Design

Begin ideating and designing assets for the outdoor map room, including obstacles, tiles and/or other scene items.

## Tasks
- [x] Create multiple design prototypes and potential ideations of outdoor map assets. (TBD)
- [x] Define general art style for outdoor map assets. (TBD)
- [x] Begin refining/iterating designs. (TBD)
- [x] Design layout and refine overall design for the outdoor map room. (TBD)
 
### Dependencies
Asset Art and Map Design Style: the designs will be dependent on the overall art style of the game and will be closely related and based on this.
 
# **Documentation**
- [Map Design](https://github.com/UQdeco2800/2021-studio-2/wiki/Map-Design)
- ...
 
# **Members**
- Amelia Rowhani (@ameliarow) (#ameliaro #6002)
