### ISSUE TITLE
<Feature> Team 5 - More Improved Attack

### ISSUE THREAD

**Issue by jac0be** [UQdeco2800/2021-studio-2#217]
# **Description**
Improve attack functionality to all weapons including:
* Better Knockback Feeling
* Weapon strong & ranged attack cooldowns

Improve weapons animations for
* Mjolnir (Thor's Hammer)
* Laevitan (Loki's Scepter)

Make one new weapon: "Longsword"
Make throw and recall functionality for Mjolnir.

# **Dependencies**
* Team 2's AI Design for Thor

# **Milestones**
- [ ] Improve Scepter animations
- [ ] Improve Hammer animations
- [ ] Implement & Design Mjolnir Throw & Recall
- [ ] Design & Implement Longsword
 
**Completion Deadline:** Oct. 5th
 
# **Extras**
- [ ] Improve Axe
 
# **Documentation**
- [MeleeWeapon](../wiki/Melee-Weapons)
- [WeaponHitboxComponent](../wiki/WeaponHitboxComponent)
 
# **Members**
- Martin Baer (@martinrbaer ) (Marty#7869)
- Jacob Edwards (@jac0be) (chrised#1330)
- Yilin Su (@suylyus) (Yilin #2263)
- Jiaao Chu (@JiaaoChu) (ChildeWhite#7324)
- Sabrina Menezes (@sabrinaleah) (bree#3373)
