### ISSUE TITLE
<Feature> Team 5 - Make Thor Boss

### ISSUE THREAD

**Issue by jac0be** [UQdeco2800/2021-studio-2#218]
# **Description**
Design assets for Thor Boss

# **Dependencies**
* Team 2's AI Design for Thor

# **Milestones**
- [x] Make Main Thor Character Design
- [ ] Make Thor walking animations
- [ ] Make Thor light attack animations
- [x] Make Thor AOE
- [ ] Make Thor throw & recall attack animations
 
**Completion Deadline:** Oct. 5th
 
# **Documentation**
- [MeleeWeapon](../wiki/Melee-Weapons)
- [WeaponHitboxComponent](../wiki/WeaponHitboxComponent)
 
# **Members**
- Martin Baer (@martinrbaer ) (Marty#7869)
- Jacob Edwards (@jac0be) (chrised#1330)
- Yilin Su (@suylyus) (Yilin #2263)
- Jiaao Chu (@JiaaoChu) (ChildeWhite#7324)
- Sabrina Menezes (@sabrinaleah) (bree#3373)
