### ISSUE TITLE
<Task> Improve Melee Weapons

### ISSUE THREAD

**Issue by jac0be** [UQdeco2800/2021-studio-2#221]
Improve base melee weapon attack.

# **Dependencies**
Team 2's enemy stun.

**Completion Deadline:** 
Aug. 5th

# **Documentation**
- [Main description of feature](../../wikis/page1)
- [JavaDoc](JavaDoc/Location/Package/Class)

# **Milestones**
- [x] Reduce knockback, in accordance with enemy stun
- [x] Add different cooldowns for strong attacks
- [x] Seperate frame counts & durations for each weapon and attack
- [x] Balance damage with enemy health.
- [x] Player needs to get stunned when attack from enemy (movement locked).
- [x] Make sure that weapons can be equipped by enemies as well as the player.
- [x] Add tests for each sub-class / weapon

# **Member**
- Jacob Edwards (@jac0be, chrised#1330)
- Sabrina Menezes (@sabrinaleah, bree#3373)
