### ISSUE TITLE
<Task> Implementation of bloodied view (TBD)

### ISSUE THREAD

**Issue by krista-b** [UQdeco2800/2021-studio-2#23]
**Feature:** Low Health Mechanic (#2 ) 
Implement a PlayerLowHealthDisplay UI component (aka bloodied view). `PlayerLowHealthDisplay` will inherit from `UIComponent` and an event handler will be added to it. It will update whenever the player's health is updated.
 
# **Dependencies**

- [ ] Bloodied View Image/textures designs

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1: Create `PlayerLowHealthDisplay` Component Class and update [Wiki Doc](https://github.com/UQdeco2800/2021-studio-2/wiki/Low-Health)  (Aug. 20)
- [x] Step 3:  Implement Code for `PlayerLowHealthDisplay` (Aug 20)
 
- [ ] Step 2: Unit Tests for `PlayerLowHealthDisplay` (29)
**Completion Deadline:** Aug. 31

# **Documentation**

# **Member**
- Rodger Xiang (@r-xian) (GGGGGGGGG#4624)
- Sadra Bayat (@sadrabt) (Sadra#9931)

**Comment by eco9898** [comment]
closed #64
