### ISSUE TITLE
[Task] Human Archer

### ISSUE THREAD

**Issue by Jonoym** [UQdeco2800/2021-studio-2#246]
This ticket is a part of Feature #200, Cutscene Implementation and Story

# Human Archer

Since the elves won't be utilised in the later areas of the game, there is only one enemy type which is the enemy warrior. To add variety to this, a basic archer will be created similar to the warrior.

## Tasks

- [x] Create the idle frames for the archer
- [x] Create the walking animations for the archer
- [x] Create the attacking animations for the archer (important)
- [x] Create the death animations

The colour scheme and many of the animations will be taken directly from the basic warrior, changing some of the proportions, weapon holding and head designs.

# **Documentation**

# **Members**
- Jonathan Tang (@Jonoym)(Jonoym#0974)
