### ISSUE TITLE
[Feature] Human Enemies

### ISSUE THREAD

**Issue by Jonoym** [UQdeco2800/2021-studio-2#247]
# Human Enemies

The only enemies that have been created are the elf enemies which will populate the Prison map along with the Elf King boss. These enemies wouldn't work very well in other areas due to the clashing art styles between the elves and the planned bosses Loki, Thor and Odin.

This feature ticket is to implement a set of sprites for human enemy types that can be easily altered to match the map they'll be placed in. Ideally, there would be different enemy types such as an archer and a warrior since this is what is currently being used for the elves. 

At first, due to time constraints, it was planned that there would only be a warrior for these areas but the time required to create the enemies was overestimated and could be done quickly due to the preexisting artworks to be used as reference. Only creating the warrior would leave a lot of code for the projectiles to go unused so creating the archer is now something that should be prioritised as well.

## Tasks

- #246 
- #248

### Archer 

- [x] Create base frames to determine if the design will fit into the game and won't cause visual clarity issues
- [x] Refine the design and obtain feedback for improvements/if the design should be further developed
- [x] Create multidirectional frames for the character
- [x] Create the walk animation for the archer
- [x] Create the death animation for the archer
- [x] Create the attack animations for the archer utilising the bow

### Warrior

- [x] Create base frames to determine if the design will fit into the game and won't cause visual clarity issues
- [x] Refine the design and obtain feedback for improvements/if the design should be further developed
- [x] Create multidirectional frames for the character
- [x] Create the walk animation for the warrior
- [x] Create the death animation for the warrior
- [x] Create the attack animations for the warrior utilising the sword

### General

- [x] Produce a set of colour schemes that would fit well with each of the 3 maps that will utilise these enemies
- [x] Create different possible head designs and clothing to match the maps
- [x] Implement the different clothing and colours onto the existing designs for each map

### Extras

- [ ] Potentially help with the AI of the boss and attacks that would align well with the mythology of the character.
- [x] Adding more variety in the AI of the enemies.

## Documentation

Design for the enemy warrior: [Enemy Warrior](Enemy-Warrior)
Design for the enemy archer: [Enemy Archer](Enemy-Archer)

## Dependencies

The implementation of the enemies will be covered by Team 2 (Enemies Team) since they have been doing most of the AI for the NPCs. This feature ticket was only for the asset creation of the enemies. Since the attack patterns of the enemies should be similar throughout the game, adding the AI tasks to suit the enemies should not be too difficult with the existing code.

# **Members**
- Jonathan Tang (@Jonoym) (Jonoym#0974)

**Comment by Jonoym** [comment]
Many human enemies have been which will fit the design of the proposed maps. The enemies have diversified their AI tasks, attack damage and move speed to create a bit of variety between the enemies. 

The AI of the boss has not been developed further due to lack of time and potentially reusing mechanics that have been created for other bosses as the team that was designated to Enemies has much greater knowledge.
