### ISSUE TITLE
[Task] Human Enemy Warrior

### ISSUE THREAD

**Issue by Jonoym** [UQdeco2800/2021-studio-2#248]
This ticket is a part of Feature #247, Cutscene Implementation and Story

# Human Enemy Warrior

Since the elves won't be utilised in the later areas of the game, there is only one other enemy type that has been planned which is the enemy warrior. To add variety to this, a basic archer will be created similar to the warrior. This means a lot of the NPC AI code will not go unused.

## Tasks

- [x] Choose a suitable design that can be refactored with different colours
- [x] Create the idle frames for the warrior
- [x] Create the walking animations for the archer
- [x] Create the attacking animations for the archer (important)
- [x] Create the death animations

The colour scheme and many of the animations will be taken directly from the basic warrior, changing some of the proportions, weapon holding and head designs.

# **Documentation**

# **Members**
- Jonathan Tang (@Jonoym)(Jonoym#0974)
