### ISSUE TITLE
<Task> Thor walking animation

### ISSUE THREAD

**Issue by suylyus** [UQdeco2800/2021-studio-2#250]
# **Description**
**Task:** [Thor walking animation](#3).
**Feature:** [Make Thor Boss](#2)

Design walking animation for thor

# **Dependencies**

- [x] Make Main Thor Character Design 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] left and right walking animation -Yilin (Sep.25)
- [x] Up walking animation -Jiaao
- [x] Down walking animation -Jiaao
 
**Completion Deadline:** Oct.5
 
# **Documentation**

# **Member**
- Yilin Su (@suylyus) (Yilin #2263)
- Jiaao Chu (@JiaaoChu) (ChildeWhite#7324)
