### ISSUE TITLE
<Task> Thor hammer attack animation

### ISSUE THREAD

**Issue by suylyus** [UQdeco2800/2021-studio-2#251]
# **Description**
**Task:** [Thor hammer attack animation](#3).
**Feature:** [Make Thor Boss](#2)

Design thor attack animation for thor

# **Dependencies**

- [x] Make Main Thor Character Design 
- [x] Thor  walking animation
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] left and right attack animation -Yilin (Sep.24)
- [x] Up attack animation -Yilin (Sep. 26)
- [x] Down attack animation -Yilin 
- [x] AOE animation -Martin
- [x] Range attack  animation -Jacob
 
**Completion Deadline:** Oct.5
 
# **Documentation**

# **Member**
- Martin Baer (@martinrbaer ) (Marty#7869)
- Jacob Edwards (@jac0be) (chrised#1330)
- Yilin Su (@suylyus) (Yilin #2263)
