### ISSUE TITLE
<Task> Character got hit animation

### ISSUE THREAD

**Issue by suylyus** [UQdeco2800/2021-studio-2#252]
# **Description**
**Task:** [Character got hit animation](#3).

Design character animation when it is hitten.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Character holding axe 
- [x] Character holding hammer
- [x] Character holding scepter
 
**Completion Deadline:** Oct.5
 
# **Documentation**

# **Member**
- Yilin Su (@suylyus) (Yilin #2263)

**Comment by Jonoym** [comment]
We already have sprites for this but they do not have the character holding the weapons.
