### ISSUE TITLE
<Task> Make Longsword

### ISSUE THREAD

**Issue by jac0be** [UQdeco2800/2021-studio-2#254]
Make new weapon: Longsword

# **Dependencies**
None

**Completion Deadline:** 
Oct. 6

# **Documentation**
- [Main description of feature](../../wikis/page1)
- [JavaDoc](JavaDoc/Location/Package/Class)

# **Milestones**
- [x] Make walking animations: Up, Down, Left, Right
- [x] Make attack animations: Up, Down, Left, Right
- [x] Make AOE attack animation
- [x] Implement weapon in code.

# **Member**
- Jacob Edwards (@jac0be, chrised#1330)
