### ISSUE TITLE
<Task> Mjolnir throw & recall

### ISSUE THREAD

**Issue by jac0be** [UQdeco2800/2021-studio-2#258]
Implement & design mjolnir throw and recall attack.

# **Dependencies**
None

**Completion Deadline:** 
Oct. 6

# **Documentation**
- [Main description of feature](../../wikis/page1)
- [JavaDoc](JavaDoc/Location/Package/Class)

# **Milestones**
- [x] Implement  mjolnir throw
- [x] Implement mjolnir rest
- [x] Implement mjolnir recall
- [x] Design animations for all the above

# **Member**
- Jacob Edwards (@jac0be, chrised#1330)
