### ISSUE TITLE
<Task> Design Thor

### ISSUE THREAD

**Issue by sabrinaleah** [UQdeco2800/2021-studio-2#259]
# **Description**
**Feature:** [Make Thor Boss](#2)

Designing the pixel art for Thor.

# **Dependencies**
None 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Design the boss, Thor (sept. 20)
- [x] redesign Thor's Hammer --- no longer doing 
- [x] Design Thor AOE attack 

 
**Completion Deadline:** Oct.5
 
# **Documentation**

# **Member**
- Sabrina Menezes (@sabrinaleah) (bree#3373)
