### ISSUE TITLE
<Task> Implement death screen on 0 health (TBD)

### ISSUE THREAD

**Issue by nichola-hettige** [UQdeco2800/2021-studio-2#27]
Feature: Low Health Mechanics (#2)

Death Screen UI component that appears when player is at 0 health and has functionalities for restarting or exiting the game

### Dependencies

- [ ] Death Screen visual assets

### Milestones
- [x] Create UI Component
- [x] Add functionality for restarting/exiting game
- [x] Attach the UI component to player's health using event handlers
- [ ] Update UI component with finalized death screen assets

**Comment by eco9898** [comment]
closed #64
