### ISSUE TITLE
[Feature] Team 3 - Odin Improvements & Win Screen Improvements 

### ISSUE THREAD

**Issue by krista-b** [UQdeco2800/2021-studio-2#279]
### Description
Drawing all animations for Odin, i.e. walking and attacking. Creating and implementing Odin's 'special attack'. Creating and implementing dialogue for Odin. Putting Odin into the game in the final map. Improving the win screen based on previous user testing and including 'You Win' text and a button to play again. 

### Milestones
- [] Odin walking animations
- [] Odin attack animations
- [] Odin special attack animations
- [] Odin Dialogue
- [] Implement Odin into final map
- [] Improve win screen

### Members
Krista Bradshaw (@krista-b) (@krista-b#4224)
Rodger Xiang (@r-xian) (@ggggggggg#4624)
Sadra Bayat Tork (@sadrabt) (@sadra#9931)
Sean Di Mario (@SeanDiMario) (@seandm#9980)
