### ISSUE TITLE
<Task> Odin walking animations

### ISSUE THREAD

**Issue by krista-b** [UQdeco2800/2021-studio-2#280]
### Description
Add animation for Odin movement

### Milestones
- [x] Design frames for Odin walking forwards, backwards, left and right
- [x] Pack textures in sprites and json file
- [x] Create animator for Odin
- [x] Add animator to Odin entity 

### Members 
Rodger Xiang (@r-xian) (@ggggggggg#4624)
Sean Di Mario (@SeanDiMario) (@seandm#9980)
