### ISSUE TITLE
<Task> Improve win screen

### ISSUE THREAD

**Issue by krista-b** [UQdeco2800/2021-studio-2#285]
### Description
Add additional features to the win screen such as a "You Won" message.

### Milestone 
- [x] Design the "You won" message
- [x] User test the Final Win Screen
- [x] Add You won message and welcome to Valhalla frames to the sprite
- [x] Reimplement the new animation for the win screen 

### Members
Krista Bradshaw (@krista-b) (@krista-b#4224)
Rodger Xiang (@r-xian) (@ggggggggg#4624)
Sadra Bayat Tork (@sadrabt) (@sadra#9931)
Sean Di Mario (@SeanDiMario) (@seandm#9980)
