### ISSUE TITLE
[Task] Human Enemy Implementation

### ISSUE THREAD

**Issue by Jonoym** [UQdeco2800/2021-studio-2#288]
This ticket is a part of Feature #286, Cutscene Implementation and Story

# Human Enemy Implementation

This task will involve adding the enemies to the Tiled file to be loaded into the game. This task is mostly code related and working with the Tiled software. 

## Tasks

- [ ] Add the enemy spawn objects to the Tiled file without any conflicts with the changes
- [ ] Implement the reader of the objects to correctly spawn the entities at the location
- [ ] Test the spawning of the enemies in the room to determine funcitonality

# **Documentation**

Documentation about the plan how the human enemies have been implemented can be found here: [Human Enemies](Human-Enemies)

# **Members**
- Jonathan Tang (@Jonoym)(Jonoym#0974)
