### ISSUE TITLE
[Task] Human Enemy Testing

### ISSUE THREAD

**Issue by Jonoym** [UQdeco2800/2021-studio-2#289]
This ticket is a part of Feature #286, Cutscene and Enemy Implementation

# Human Enemy Testing

This task will be used to determine whether changes are needed for the design of the characters and balancing for the number of characters per room and their Combat stats. This task can also be used to update the AI of the enemies if changes will improve the gameplay quality greatly.

## Tasks

- [x] Create a testing branch that contains some of the enemies for each of the areas
- [x] Carry out User Testing to determine how players are finding the attack gameplay
- [x] Use feedback to update the gameplay 

# **Documentation**

Documentation about the plan how the human enemies have been implemented can be found here: [Human Enemies](Human-Enemies)

# **Members**
- Jonathan Tang (@Jonoym)(Jonoym#0974)

**Comment by Jonoym** [comment]
Adjustments have been made to the damage, move speed and stun time duration of the enemies so they feel more fair to play against.
