### ISSUE TITLE
[Task] Loki Characteristics

### ISSUE THREAD

**Issue by Jonoym** [UQdeco2800/2021-studio-2#290]
This ticket is a part of Feature #287,Design of Loki

# Loki Characteristics

To have well thought out bosses, we need to consider the characteristics behind the character, their motives, attacks, dialogue, etc. When designing the character, defining how the character would act will help with deciding what types of attacks would be implemented by character.

We want to take the original Mythology behind the god, Loki, into consideration to have an accurate representation of the character. Using the Marvel depiction of the god could also be used to determine how we think the character should act.

## Tasks

- [x] Define the type of character that Loki is, determined by their motives
- [x] Create a list of tasks that could be implemented into Loki for attack gameplays that reflect the characteristics
- [x] Update the dialogue and storyline to reflect this well

# **Documentation**

The design for Loki can be found here: [Loki](Loki), this will also display the choices behind the AI tasks for the boss.

More about the characteristics and AI of Loki is shown here: [Characteristics and Behaviour](Loki-Characteristics-and-Behaviour)

# **Members**
- Jonathan Tang (@Jonoym)(Jonoym#0974)
