### ISSUE TITLE
[Task] Loki AI 

### ISSUE THREAD

**Issue by Jonoym** [UQdeco2800/2021-studio-2#291]
This ticket is a part of Feature #287, Design of Loki

# Loki AI

Currently, the Loki boss only has reused AI from the Elf King. To diversify the gameplay between bosses, we need to design different AI for the boss to differentiate themselves. These tasks will be based on the boss characteristics that have already been defined. 

## Tasks

- [x] Decide on which tasks are both feasible and would create an interesting attack gameplay
- [x] Create the projectiles that would be used by Loki
- [x] Test the attack gameplay and balance accordingly
- [x] Carry out user testing to determine if boss fight is both completable yet challenging

# **Documentation**

The design for Loki can be found here: [Loki](Loki), this will also display the choices behind the AI tasks for the boss.

More about the characteristics and AI of Loki is shown here: [Characteristics and Behaviour](Loki-Characteristics-and-Behaviour)

Information about the implementation of the tasks can be found here: [Loki Tasks](Loki-Tasks)

# **Dependencies**

This task will be dependent on the previous task #290 in order to start implementing the AI.

# **Members**
- Jonathan Tang (@Jonoym)(Jonoym#0974)
