### ISSUE TITLE
[Task] Cutscene Testing

### ISSUE THREAD

**Issue by Jonoym** [UQdeco2800/2021-studio-2#292]
This ticket is a part of Feature #286 , Design of Loki

# Cutscene Testing

Before implementing everything into the Tiled set as well as the game. The current plan for the cutscenes should be tested and determine if any changes could create a better experience for the player. To do this, a test branch will be created to allow users to explore the maps and trigger cutscenes at their respective places. 

## Tasks

- [x] Create the User testing branch with an entire map area filled with cutscenes
- [x] Carry out User testing to determine if changes should be made to the current system
- [x] Update the plan and add features based on the feedback received from the testing

# **Documentation**

The plan that is currently in place for the dialogue can be found here [Dialogue](Dialogue). This will be updated with the results of the User Testing and any iterative improvements that have been done

# **Dependencies**

This task is not dependent on anything else since the base map has already been created.

# **Members**
- Jonathan Tang (@Jonoym)(Jonoym#0974)
