### ISSUE TITLE
[Task] Cutscene Implementation

### ISSUE THREAD

**Issue by Jonoym** [UQdeco2800/2021-studio-2#293]
This ticket is a part of Feature #286, Cutscene and Enemy Implementation

# Loki AI

After receiving the feedback for the implementation of the cutscenes, it should be implemented into the Tiled file which will allow for easier implementation into the game. These cutscenes need to planned out well before implementing it into the Tiled file as repeatedly changing the file can lead to loss of work when conflicts occur.

## Tasks

- [x] Add the objects to start the cutscenes into the Tiled file
- [x] Implement the code to read the JSON file and trigger the spawning of the Cutscene triggers
- [x] Test that the cutscenes are working appropriately with the current system in conjunction with the enemy and boss spawns.

# **Documentation**

The design for Loki can be found here: [Loki](Loki), this will also display the choices behind the AI tasks for the boss.

# **Dependencies**

This task will be dependent on the previous task #292  in order to start implementing the cutscenes into the game

# **Members**
- Jonathan Tang (@Jonoym)(Jonoym#0974)
