### ISSUE TITLE
[Task] Cutscene Improvements

### ISSUE THREAD

**Issue by Jonoym** [UQdeco2800/2021-studio-2#294]
This ticket is a part of Feature #286, Cutscene and Enemy Implementation

# Cutscene Improvements

Some improvements need to be made to the current cutscene implementation to make them more generic and easy to implement. Ideas for this currently is to block off the boss room with the use of cutscene triggers that will allow movement once all of the enemies have been defeated.

Other types of cutscenes that should be implemented is that the movement cutscenes should be more generic and force the player to move in certain directions. This would also require the implementation of a trigger to stop the movement and locking of the player.

The additions of the generalised trigger would allow the spawning into the Tiled map be easier and independent from parameters such as distance to walk.

## Tasks

- [x] Add an entity that will block the player from proceeding if there are still some entities alive
- [x] Generalise the movement cutscene triggers to walk in the 4 basic directions of movement
- [x] Create a cutscene trigger to unlock the player and allow input after the cutscene has occurred.

## Bugs

- [ ] Keyboard inputs are currently being registered during the cutscene however this should not be allowed.

# **Documentation**

The implementation of the cutscenes can be found here [Cutscene Implementation](Cutscene-Implementation) and this will be updated once the new cutscenes have been added.

# **Dependencies**

This task can be carried out independently from other tasks as the implementation of the cutscenes has already been finished.

# **Members**
- Jonathan Tang (@Jonoym)(Jonoym#0974)
