### ISSUE TITLE
[Task]  Code Clean Up

### ISSUE THREAD

**Issue by Jonoym** [UQdeco2800/2021-studio-2#296]
# Code Clean Up

There are a lot of duplications, code smells and security issues in the latest version of main as of the end of the sprint. 

## Tasks

- [ ] Remove all of the code smells relating to commented out code by the end of the sprint
- [ ] Remove all of the security issues that are recorded by Sonar Cloud
- [ ] Remove all bugs recorded by Sonar Cloud
- [ ] Attempt to reduce the amount of duplication in the code 
- [ ] Add tests for possible parts of the code that can be unit tested
