### ISSUE TITLE
<Feature> Team 5 - Music Themes For Each Area

### ISSUE THREAD

**Issue by jac0be** [UQdeco2800/2021-studio-2#297]
Make songs for each level and boss. Each song will represent the characteristics of the level, and the characteristics of the boss.

# **Dependencies**
None

**Completion Deadline:** 
Oct. 19

# **Documentation**
- [Main description of feature](../../wikis/page1)
- [JavaDoc](JavaDoc/Location/Package/Class)

# **Milestones**
- [x] Make, or improve, song for beginning level.
- [x] Make song for Loki / Lava level
- [x] Make song for Thor / outdoor / palace exterior level
- [x] Make song for Odin / Palace Interior

# **Member**
- Jacob Edwards (@jac0be, chrised#1330)
