### ISSUE TITLE
[Feature] Sprint 1: Character Attack

### ISSUE THREAD

**Issue by martinrbaer** [UQdeco2800/2021-studio-2#3]
# **Description**
The basic character attack needs to be added. This is specifically the design choices of the weapons and the specifications of multiple weapons and how the weapons will affect enemies and the environment.
 
## **Examples**
- **Axe**: The starting weapon for the player. Has specific sounds & animations.

# **Dependencies**
The sprite of the main character holding a weapon relies on the sprite of the main character. (Which I believe Amelia will be starting)
 
# **Milestones**
- [x] Creation of the weapon class in java (Aug. 25)
- [x] Conceptualising the artwork for one weapon (Aug. 25)
- [x] Creating the attack animation for one weapon (Aug. 31)
- [x] Implementing the actual attack and triggering the animation (Aug. 31)
- [x] Getting the attack to interact with other entities (Aug. 31)
 
**Completion Deadline:** Aug. 30
 
# **Extras**
- [ ] Secondary attack specific to the weapon
 
# **Documentation**
- [Main description of feature](../../wikis/page1)
 
# **Members**
- Martin Baer (@martinrbaer ) (Marty#7869)
- Jacob Edwards (@jac0be) (chrised#1330)
- Yilin Su (@suylyus) (Yilin #2263)
- Jiaao Chu (@JiaaoChu) (ChildeWhite#7324)
- Sabrina Menezes (@sabrinaleah) (bree#3373)

**Comment by zenzlia** [comment]
Please make your description a little longer, apart from that it is looking good
