### ISSUE TITLE
[Feature] Team 2 - Minion combat and Boss fights part 3

### ISSUE THREAD

**Issue by MTbir** [UQdeco2800/2021-studio-2#300]
# Description 
This sprint we are finishing off [sprint 3](181), typically fine tune the animation and implement enemy to the level.

#  Milestones 
## Design and animations: 
- [ ] #125
- [ ] Fix enemy animation - elf designs are inconsistent

## Sound effect:
- [ ] Death enemy sound effect

## Combat
- [ ] Boss enemy has passive healing until all the enemies are dead and is invincible

## Attacks
- [ ] Use player like weapon system
- [ ] Hel attacks
  - [ ] Create lava trap
- [ ] Tyr attacks
  - [ ] Throw and retrieve spear
  - [ ] #234
- [ ] Loki attacks
  - [ ] Create fake loki
  - [ ] Teleport without vortex to hide with duplicates
  - [ ] Other magic based attacks

## Debug
- [ ] Tidy up code
- [ ] Check code smell
- [ ] Check code coverage
- [ ] Debug error

# Members
- Fleur Nicholson (@FleurN21) Fleur#0608
- Minh Tieu (@MTbir) Minh#7523
- Eli Cox (@eco9898) .♡.𝓮𝓵𝓲.♡.#5723
- Kai Barry (@BobJohnsom) BOBJohnson#5476
- Haopeng Xia (@HaoPengXia) HaoPengXia(Barney)#8321
