### ISSUE TITLE
[Feature] Fix up Thor designs + code 

### ISSUE THREAD

**Issue by sabrinaleah** [UQdeco2800/2021-studio-2#307]
# **Description**
In the last sprint we received user feedback on our Thor designs, some of the following tasks are based on what participants said. There are also small design and code discrepancies that haven't been fixed from past sprints. 

# **Dependencies**
List any features on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a feature needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on.

e.g. Random game mode relies on random map seed generation(#xx).

# **Milestones**
- [ ] Recolor Thor (Oct. 15) 
- [ ] Fix Thor's left and right movement (Oct. 17)
- [ ] Fix Thor AOE attack - code and design (Oct. 17)
- [ ] Hammer lightening sounds Oct. 17)

**Completion Deadline:** Oct. 17  

# **Extras (optional)**
- [ ] Thor throw attack 

# **Documentation**
- [Main description of feature](../../wikis/Match%20Gameplay%20Rule%20Set)
- [User documentation](../../wikis/Game-Guide#section-five-cards)
- ...

# **Members**
- Martin Baer (@martinrbaer ) (Marty#7869)
- Jacob Edwards (@jac0be) (chrised#1330)
- Yilin Su (@suylyus) (Yilin #2263)
- Jiaao Chu (@JiaaoChu) (ChildeWhite#7324)
- Sabrina Menezes (@sabrinaleah) (bree#3373)
