### ISSUE TITLE
<Task> Recolour Thor 

### ISSUE THREAD

**Issue by sabrinaleah** [UQdeco2800/2021-studio-2#308]
# **Description**
**Feature:** [Fix up Thor designs + code](#307)

Recolouring Thor's cape and hair

# **Dependencies**
- [x]  Decide on new colours and send out to team (Sabrina)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x]  Decide new colours and recolour front, back, left, right single frames (Sabrina)
- [x]  Recolour left and right walking (Yilin)
- [x]  Recolour up and down walking (Benson)
- [x]  Recolour all angles for hammer attack (Yilin)
- [x]  Recolour AOE (Sabrina)

**Completion Deadline:** Oct. 15
 
# **Documentation**

# **Member**
- Sabrina Menezes (@sabrinaleah) (bree#3373)
- Yilin Su (@suylyus) (Yilin #2263)
- Jiaao Chu (@JiaaoChu) (ChildeWhite#7324)
