### ISSUE TITLE
<Feature> Revised Attack Mechanics

### ISSUE THREAD

**Issue by jac0be** [UQdeco2800/2021-studio-2#310]
# **Description**
Balance weapons and make minor additions / modifications to each weapon in order to improve attack mechanics.

# **Dependencies**
None

# **Milestones**
- [x] Longsword AOE Attack Animations (Oct. 17)
- [x] Fix attack animation override (Oct. 17)
- [x] Axe & Hammer Left attack animation fix (Oct. 17)
- [x] Scepter Ranged Animations (Oct. 17)
- [x] Scepter Projectile Animations (Oct. 17)

**Completion Deadline:** Oct. 17  

# **Extras (optional)**

# **Documentation**
- [Main description of feature](../../wikis/Match%20Gameplay%20Rule%20Set)
- [User documentation](../../wikis/Game-Guide#section-five-cards)
- ...

# **Members**
- Martin Baer (@martinrbaer ) (Marty#7869)
- Jacob Edwards (@jac0be) (chrised#1330)
- Jiaao Chu (@JiaaoChu) (ChildeWhite#7324)
- Sabrina Menezes (@sabrinaleah) (bree#3373)
