### ISSUE TITLE
<Task> Design main menu screen (TBD)

### ISSUE THREAD

**Issue by krista-b** [UQdeco2800/2021-studio-2#33]
Feature: Low Health Mechanic (#2 )
Design main menu screen and create assets for it

### Milestones

- [x] Design background image
- [x] Design title card
- [ ] Design button drawables

### Members
Sean Di Mario (@SeanDiMario) (@seandm#9980)

**Comment by eco9898** [comment]
closed #64
