### ISSUE TITLE
<Task> Implement main menu screen (TBD)

### ISSUE THREAD

**Issue by krista-b** [UQdeco2800/2021-studio-2#35]
Feature: Low Health Mechanic (#2)
Implement the newly designed main menu 

### Dependencies 
Require the creation and finalization of art assets for the menu
- [x] Main menu art assets (#33)
- [ ] Main menu design user testing

### Milestones
- [ ] Create json file for skin class of the components
- [x] implement the background image 
- [x] implement the title card
- [ ] implement the UI component design style

### Members
Sadra Bayat Tork (@sadrabt) (@sadra#9931)

**Comment by eco9898** [comment]
closed #64
