### ISSUE TITLE
Team 1 - Sprint One Features - Player Design, Basic Movement, Camera, Dialogue and Health Display

### ISSUE THREAD

**Issue by GreyAtlantean** [UQdeco2800/2021-studio-2#4]
# Player Design, Basic Movement and Camera Tracking

## Player Design - Task Ticket #7 

We plan on creating possible character designs for how the character model will appear in the game. This will be a basic sprite of the character to be used as a placeholder. The design will be refined later on to match the art style of the enemies and the generated map. 

### Milestones 

- [x] Multiple pixel character design concepts (23th August)
- [x] Finalise the initial character design to be developed (26th August)
- [x] Refine design (TBD)
- [x] Have basic walk animation complete (29th August)

## Basic Movement - Task Ticket #9 

Player will be able to move around the screen using keyboard input along with movement abilities. The character will have abilities such as dashes and dodges which will be worked on as well. The player will move with WASD for an 8-direction movement system. 

### Milestones 

- [x] #49 (18th August)
- [x] #9 (20th August)
- [x] Player able to move in basic cardinal directions (18th August)
- [x] Player able to move diagonally as well (18th August)
- [x] Player has a dash ability (20th August)
- [x] Player is able to sprint around the map (20th August)

### Extras

- [x] Collision handling against terrain and enemies (27th August)
- [x] The player speed matches well with the animations and size of the map (Dependent on Player Animations)

## Basic Camera Tracking - Task Ticket #11

The camera will track the player and keep them centred on screen as they move around the map. This will allow the player to be focus of the game as they travel through a large map. The camera will ideally stop moving once close to the borders of the map for a better experience. Camera movement will be dependent on how the map is generated. 

### Milestones 

- [x] #11
- [x] Camera follows player around (22nd August)
- [x] Test and decide on a suitable zoom on the character (Dependent on Character Design/Enemies)

### Extras

- [ ] Camera will stop at edges of the map (Dependent on Map Design)

### Dependencies
- The tracking of the Character will be dependent on the implementation of the map.
- Collision of the Character will depend on the types of objects and walls of the map.

## Come up with story and dialogue system in game - Task Ticket #14 

As we want the gods to be able to converse with the player we will need a way to have dialogue in game. The dialogue will help provide insight into the storyline to give the player a better understanding of what the game is about. This allows us to convey the characteristics and qualities of each character in the game. 

### Tasks

- [x] #14 (23rd August)
- [x] Have the basic progression for the character laid out
- [x] #48 (23rd August)

### Extras

- [ ] Refine the system (30th August)
- [x] Get in game events to trigger the dialogue (Stretch Goal)

## Cutscenes
Create cutscenes that would be triggered by in game effects. The cutscene should be able to move the player and allow the player to interact with enemies with the use of dialogue. The cutscene should be skippable with the use of an escape key which will finish the cutscene as if it was played through.

### Tasks

- [x] Get a working cutscene (28th August)
- [ ] Create the story behind the cutscene (29th August)
- [ ] Move the character while the cutscene is playing (30th August)

### Extras

- [x] Add a key to escape out of the entire cutscene. (29th August)
- [x] Create an in game trigger for the cutscene to occur. (Could be on game start)

## Health and Ability UI
Currently the Health is displayed with the use of text and this can be difficult to see while playing the game. A visual representation using a Health bar is to be created so a quick glance to the corner of the screen provides satisfactory information. Abilities should not be able to be used in quick succession so an interface to show that the ability is currently on cooldown should be shown. 

### Tasks

- [x] The health bar is displayed as a red bar that updates consistently. (27th August) #71
- [x] Create the UI of the health bar and abilities to match the game art style. (28th August) #70
- [x] Display the sprites on a suitable location on the screen and decide on the position and size. (29th August) #70

### Extras

- [ ] The health bar does not change in a single frame but will slowly decrease. (30th August) #71

### Dependencies

- Weapons and weapon attacks from team 5 to allow us to finish off the sprites for the main character.
- The initial camera and player position will depend on how the map is situated so will be reliant on the map design by Team 4.

# **Documentation**
- [Main Character Design](https://github.com/UQdeco2800/2021-studio-2/wiki/Main-Character-Design)
- [JavaDoc](JavaDoc/Location/Package/Class)

 
# **Members**
- Jonathan Tang (@Jonoym) (Jonoym#0974)
- Muhammad Pathan (@GreyAtlantean) (Grey Atlantean#0010)
- Josephine Wong (@CuteCinnamonRoll) (;)#1576)
- Amelia Rowhani (@ameliarow) (ameliaro#6002)
- Carlos Liu (@Carloslyx) (Carlos Liu#6008)

**Comment by eco9898** [comment]
Will the player be able to aim with the mouse for melee/ranged attacks in sprint 1 or any later sprint?

**Comment by GreyAtlantean** [comment]
For ranged attacks yes, however normal attacks will likely just go in the direction the player is facing. Ranged attacks will probably be future sprint thing though.
