### ISSUE TITLE
<Task> Character Movement Sprites

### ISSUE THREAD

**Issue by Jonoym** [UQdeco2800/2021-studio-2#42]
# Player Sprites Design

**Task:** Create sprites to match with the movement of the character.
**Feature:** This ticket is part of Feature #4, Player Design
 
Create sprite frames based on the Character Design to animate the walking of the character in multiple directions that they will face. The player will have idle frames for up, down and sideways. 

## **Example**
- **Direction Based Images**: The character will face different directions that is dependent on the inputs of the player.
- **Animation**: The character will look like they are walking through the map. 

 ## **Dependencies**

- [x] Art and Character Style (#7 ) The sprites will be dependent on the overall art style of the game and the finalisation of the design of the character as the frames will be closely related and based on this.
 
e.g.
- [x] An overall character design needs to be made which other sprites will be based on.

# **Milestones**
List of steps that need to be completed for this task.
- [x] Add different frames for each movement type. (Aug. 26)
- [x] Create basic initial frames for sideways movements (left/right walking). (Aug. 29) 
 
**Completion Deadline:** Aug 30.

# **Documentation**
- [Main Character](https://github.com/UQdeco2800/2021-studio-2/wiki/Main-Character)
- [Main Character Design](https://github.com/UQdeco2800/2021-studio-2/wiki/Main-Character-Design)
- [Main Character Animation Frames](https://github.com/UQdeco2800/2021-studio-2/wiki/Main-Character-Animation-Frames)

 
# **Member**
- Amelia Rowhani (@ameliarow) (#ameliaro #6002)
- Carlos Liu (@Carloslyx) (Carlos Liu #6008)
