### ISSUE TITLE
<Task> Design axe

### ISSUE THREAD

**Issue by sabrinaleah** [UQdeco2800/2021-studio-2#46]
# **Description**
**Task:** [Design axe](#46 ).
**Feature:** [[Feature] Sprint 1: Character Attack](#3  ).

Create deigns for the axe and animate axe movements. 

# **Dependencies**
- [x] Character design need to be completed to create the animation (#xx)
- [x] Art style of game map, character and enemies (#xx)

# **Milestones**
List of steps that need to be completed for this task.
- [x] First draft pixel art (Aug. 22) (Sabrina)
- [x] Finalise pixel art (Aug. 25) (Sabrina)
- [x] Animation and character holding axe and spear: left and right movement (Aug. 29) (Yilin)
- [x] Animation and character holding axe and spear: front and back movement (Aug. 29) (Sabrina)

 
**Completion Deadline:** Aug. 31

# **Documentation**
- [Main Character: Weapons](https://github.com/UQdeco2800/2021-studio-2/wiki/Main-Character#weapons)
 
# **Member**
- Sabrina Menezes (@sabrinaleah ) (bree#3373)
- Yilin Su(@suylyus ) (Yilin#2263)
