### ISSUE TITLE
<Task> Design Spear

### ISSUE THREAD

**Issue by suylyus** [UQdeco2800/2021-studio-2#47]
# **Description**
**Task:** [Design axe](#46 ).
**Feature:** [[Feature] Sprint 1: Character Attack](#3  ).

Create designs for the axe and animate spear movements. 

# **Dependencies**
- [x] Character design need to be completed to create the animation (#xx)
- [x] Art style of game map, character and enemies (#xx)

# **Milestones**
List of steps that need to be completed for this task.
- [x] First draft pixel art (Aug. 22)
- [x] Finalise pixel art (Aug. 29)
- [x] Character holding spear(Aug. 29)
 
**Completion Deadline:** Aug. 25

# **Documentation**
- [Main Character: Weapons](https://github.com/UQdeco2800/2021-studio-2/wiki/Main-Character#weapons)
 
# **Member**
- Yilin Su (@sulyus ) (Yilin #2263)
