### ISSUE TITLE
<Task> Interactive Speech Boxes

### ISSUE THREAD

**Issue by Jonoym** [UQdeco2800/2021-studio-2#48]
This ticket is a part of Feature #4, Camera Movement, Story, Player Design and Dialogue

# Dialogue

The game wants to immerse the player into the game and understanding the storyline is a big aspect of that. We want to convey the backstory through dialogue between the main character and the bosses to provide insight to what is happening. 

We want the text boxes to be an addition to the game, some players may not focus on the storyline and that is okay, the story will be conveyed through the game as well for those who want to get right in to the fighting.

## Milestones

- [ ] Choose a font to use for the game, this will match the overall art style
- [x] Have the ability to display text on the screen
- [x] Have a way to allow the player to remove text off the screen with either a button or clicking it
- [x] Have a way to queue up text to display after the player has read the previous dialogue screen

### Extras

- [x] Have a way to trigger dialogue to occur
- [x] Implement a way to escape out of all dialogue

### Dependencies

The text boxes need to be triggered by in game events so this will depend on movements, bosses and changing rooms within the game.

**Completion Deadline:** August 25th.
 
# **Documentation**
[Camera Tracking](Camera-Tracking)
 
# **Members**
- Jonathan Tang (@Jonoym) (Jonoym#0974)

**Comment by Jonoym** [comment]
Font style is very dependent on the art style of the game. None of the art style has been properly defined and current font fits with the pixel style so it may not be necessary to change. If further development of the art occurs and the font looks out of place, changing the style may need to be reevaluated.
