### ISSUE TITLE
<Task> Fix Character Movement

### ISSUE THREAD

**Issue by Jonoym** [UQdeco2800/2021-studio-2#49]
# Movement

**Feature:** Player Movement #4. 

Movement of the main character has been taken care of by the game engine but it currently contains some inconsistencies in how the character moves diagonally. When moving the character diagonally, the velocity of the character is not constantly at 1 but will be 1.4x the original speed.

## Milestones
- [x] Test and finalise a walking speed for the character.
- [x] Change diagonal movement to keep and constant walk speed.

### Extras
- [x] Test how a sprinting feature feels with the movement.
- [x] Implementation of a dash movement ability
- [x] Decide on which keys will control the characters attack and movement.

## Documentation
[Player Input and Controls](Player-Input-and-Controls)

### Members
- Jonathan Tang (@Jonoym)(#Jonoym#0974)
