### ISSUE TITLE
<Task> Attack keyboard input

### ISSUE THREAD

**Issue by jac0be** [UQdeco2800/2021-studio-2#50]
Map player input controls to allow players to attack using an equipped weapon,
also pass click location parameters to event handler, to determine direction of attack.
Lock player movement when attacking.

# **Dependencies**
-  #13 

**Completion Deadline:** Aug. 29
 
# **Documentation**
- [Main description of feature](../../wikis/page1)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...

# **Milestones**
- [x] Map mouse controls to attack event, ensure event is triggered through input
- [x] Implement entity movement lock when entity is attacking
- [x] Create tests to test the above two functions

# **Member**
- Jacob Edwards
