### ISSUE TITLE
<Task> Weapon hitbox collision detection

### ISSUE THREAD

**Issue by jac0be** [UQdeco2800/2021-studio-2#53]
Implement weapon collision detection, as well as apply health reduction, knockback, etc.
Define onCollisionStart function that applies weapon effects to an entity that is hit by a weapon.

# **Dependencies**
- [x] #52 

**Completion Deadline:** Aug. 31
 
# **Documentation**
- [Main description of feature](../../wikis/page1)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...

# **Milestones**
- [x] Implement event handler for weapon collision
- [x] Apply weapon effects such as knockback, health reduction, to enemy entity
- [x] Create tests to test the above two functions

# **Member**
- Jacob Edwards, Martin Baer
