### ISSUE TITLE
<Task> Make intial game music

### ISSUE THREAD

**Issue by jac0be** [UQdeco2800/2021-studio-2#55]
Try to develop a main-video game theme to be played in the main menu, as well as any other area/boss themes that might be neccesary if time allows. Use a traditional 8-bit sounding music theme, to fit in with pixel-art atmosphere of the game.

Main theme will be high-tempo, high energy, and hopefully really catchy!
Area themes will be matched to the atmosphere of the area (TBD).
Boss themes will be matched to the atmosphere of the boss arena, and the personality of the boss (TBD)

# **Dependencies**
-  None

**Completion Deadline:** Aug 31.
 
# **Documentation**
- [Main description of feature](../../wikis/page1)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...

# **Milestones**
- [x] Create, & synthesise a good 8-bit melodic sound using waveforms.
- [x] Find, or create 8 bit drums.
- [x] Make a main-theme.

#**Extras**
- Start creating other soundtracks to be used in areas
- Start making other soundtracks to be used in boss arenas

# **Member**
- Jacob Edwards
