### ISSUE TITLE
[feature] Room Generation

### ISSUE THREAD

**Issue by GoldMan93** [UQdeco2800/2021-studio-2#6]
# Description
A basic room generation will be created. This includes walls, obstacles, entries, exits, traps, size of room.

# Milestones
## Map Design
- [x] Understand engines limits 
- [x] Concept art for pixelated or line based 
- [x] Create placeholder Wall texture/art
- [x] Create placeholder Trap texture/art 
- [x] Create placeholder Floor texture art 

## Map Functionality
- [x] Empty square room, loaded in-game 
- [x] Create Trap (harms player) object 
- [ ] Import Obstacle placement

# Dependencies
- Collaborate with Team 1 for interaction between player and room
- Collaborate with Team 2 for interaction between enemies and room

# Documentation
[Wiki](https://github.com/UQdeco2800/2021-studio-2/wiki)

# Members
Benjamin Gonzalez (@BenjaminGonzalez) (Benjamin-Gonzalez-#2927)
Sicheng Pan (@GoldMan93) (GW.Goldman#8858)
William Parker (@parker334) (parker334#2323)
Nicolas Armstrong (@Nicolas-Armstrong) (FalconLuma#3614)
Quan Tran (@othiem) (Quan Tran#0165)

**Comment by eco9898** [comment]
Would it be possible for a type of trap to be an enemy hive that summons more enemies? Team 2 was planning on having a hive based enemy that would protect a hive object on the map, this could work well with your trap idea. We, likely, wouldn't be added hive enemies until sprint 2 though.

**Comment by GoldMan93** [comment]
> Would it be possible for a type of trap to be an enemy hive that summons more enemies? Team 2 was planning on having a hive based enemy that would protect a hive object on the map, this could work well with your trap idea. We, likely, wouldn't be adding hive enemies until sprint 2 though.

If mark the hive as a type of object. When we code the generate trap code.  Just swap some of them randomly to the hive won't be too hard I think. It is possible to do so.

**Comment by zenzlia** [comment]
Hey please make sure to break this feature ticket into smaller task tickets

**Comment by parker334** [comment]
All implemented except for importing obstacle placement.
