### ISSUE TITLE
<Task> Enemies can call out to nearby enemies when they find the player

### ISSUE THREAD

**Issue by MTbir** [UQdeco2800/2021-studio-2#60]
# **Description**
**Task:** Enemies can call out to nearby enemies when they find the player
**Feature:** [Team 2 - Minion enemy movement](5) 
 
Add an alert component to all ghost entities. Once the alert is triggered, all the enemies get a buff to their view range and head towards the alerting ghost.
Only the ghost King entity can trigger the alert and will only affect other ghosts if the Ghost King has seen the player for longer than 3 seconds. If the ghost king loses sight of the player then the alert will stop and all other ghosts go back to their normal function.

- [x] Have a modified chasetask for the ghost king that will trigger an event after 3 seconds
- [x] Have a modified chaseTask for the normal ghosts that will override is Visible after the event is called
- [x] Implement some way for each ghost to read/send the event

**Completion Deadline:** Aug. 28

# **Documentation**
- [AI Wiki](../wikis/AI)
 
# **Member**
- Ming (@MTbir) (Minh#7523)
- Eli (@eco9898 ) (.♡.𝓮𝓵𝓲.♡.#5723) (helping in person and with design idea)

**Comment by MTbir** [comment]
**Description**: Add alert component to all ghost entity (unaffected ghost entities functionality) - Once the alert is trigger (all the enemies get buff so they can detect and chase the player twice as far)

**Entity**: Only the ghost King entity can trigger the alert and only trigger if the player in detect range of the ghost king for more than 3 seconds. If the ghost king lose sight of player then the trigger will switch off and all other ghosts back to their original function.
