### ISSUE TITLE
<Task> Cut Scenes 

### ISSUE THREAD

**Issue by CuteCinnamonRoll** [UQdeco2800/2021-studio-2#67]
This ticket is a part of Feature #4, Cutscenes and Dialogue

# Cut scenes

Implement cut scenes where player will trigger dialogue when in the proximity of a NPC. This should only work for particular enemies i.e. bosses. Depending on the NPC that the player is interacting with, the dialogue should change appropriately.  

## Milestones

- [x] Create "special" NPC and have dialogue pop up when player gets close to them.
- [ ] Have the player move towards the NPC without player input. 

### Extras

- [x] Add a key to escape out of the entire cut scene to the end point. 
- [x] Create an in game trigger for the cut scene to occur.

### Dependencies
Cut scenes will implement text boxes and will be triggered by bosses. 

**Completion Deadline:** August 28th.
 
# **Documentation**
[Camera Tracking](Camera-Tracking)

# **Members**
- Josephine Wong (@CuteCinnamonRoll) (;)#1576)

**Comment by Jonoym** [comment]
Movement of the main character within a cutscene is dependent on how the map is situated, currently controlling the player from the trigger is doable as shown by making the character stop so implementation will not be too difficult, just dependent on where we want the character to move to.
