### ISSUE TITLE
[Feature] Team 1 - Sprint 2 - Cutscenes, Saving and Further Character Design

### ISSUE THREAD

**Issue by GreyAtlantean** [UQdeco2800/2021-studio-2#84]
# Dialogue Update, Save System, Additional Asset Design Work 

# Cutscenes, Dialogue and Tutorial

Addition of cutscenes to the game will help introduce the story behind the game which will be important to some of the players. 

## Task Ticket Links

- #93
- #105
- #106 
- #107
- #108
- #114 

### General Implementation

- [x] Make the character move once triggering a cutscene entity (4th August)
- [x] Produce a set of different dialogues for each boss that will randomise so there is variety on runs (6th August)
- [x] Alternating between the main character moving and a new text box popping up (6th August)
- [x] Keyboard input during the cutscene can both change where the player is moving as well as progression of the text (10th August)
- [x] Randomly select dialogue when meeting a character past the first time
- [x] Choose dialogue based on whether you have defeated a character in the past or not

### Display 

- [x] Dialogue between the bosses should alternate the character behind the text box to display who is talking. This could possibly be shown by the position of the text box.
- [x] Higher quality version of the text box as a basis.

### Tutorial

- [x] Produce a set of dialogue that would be suitable for the tutorial of the game
- [ ] The tutorial will be optional and will only show for first time users
- [x] The dialogue in the tutorials will alternate between allowing the player to try moving and attacking
- [x] Use dialogue triggers to play the next part of the tutorial once the character moves to a certain point or kills a dummy target

### Extras

- [ ] The game will remember if the player has talked to the boss before, the dialogue will change accordingly.
- [x] Keyboard input during the cutscene can both change where the player is moving as well as progression of the text (10th August)
- [x] The text box display can change depending on the map the player is currently on.
- [x] More detailed version of the main character and bosses. 

### Dependencies
Currently, there is no way to kill enemies and there are no bosses so event triggers will be used in place at the moment to trigger the cutscenes which will be later moved over to entering a boss room or defeating a boss. Cutscenes should involve someone talking to the main character, revealing new information about mechanics of the game or the story. Since the main character is progressing through the map, forcing movements during the cutscenes to lead the main character has been chosen to go alongside dialogue between the character.

The game will check the save statistics to determine the type of dialogue that should be used. This will heavily depend on how the save system works.

## Save/Load System

- [x] Design a save format
- [ ] Implement a way to get events and update a save file per the format
- [ ] Have the ability to load the save into the game

## Asset Design Work and Animations

Continuation, testing and refinement of asset and character design, including designing the main character's death and text box style. Map assets will also be ideated and designed, including potential obstacles, tiles and/or other scene items, as well as a more defined map colour scheme. 

### Task Ticket Links

- #109 
- #110 
- #112 
- #113 

### Main Character
- [x] Begin user testing of character/map asset design (TBD)
- [x] Potential changes to designs (TBD)
- [x] Design of bloody/injured character before death (TBD)
- [x] Death animation of the main character (TBD)

### Extras (Main Character)

- [ ] Add effects to the character when dashing (TBD)
- [ ] Add a blur effect to the main character (TBD)
- [x] Design death screen

### Text Box

- [x] Refinement of character text box design (TBD)
- [x] Scale up image of the main character to go alongside text box (TBD)

### Map Assets

- [x] Begin design and ideation of obstacle assets for map design (TBD)
- [x] Begin designing tile assets
- [x] Begin designing decoration tile assets
- [x] Begin user testing of map and map asset designs (TBD)
- [x] Refine and iterate designs

# **Members**
- Jonathan Tang (@Jonoym) (Jonoym#0974)
- Muhammad Pathan (@GreyAtlantean) (Grey Atlantean#0010)
- Amelia Rowhani (@ameliarow) (ameliaro#6002)
- Carlos Liu (@Carloslyx) (Carlos Liu#6008)

**Comment by Jonoym** [comment]
Issues with the tutorial and save file. Will be looked at when bosses and a proper map has been implemented to an acceptable degree.
