### ISSUE TITLE
[Feature] Team 3 Player Health Regeneration 

### ISSUE THREAD

**Issue by krista-b** [UQdeco2800/2021-studio-2#85]
### Description 
Addition of a crate which when attacked drops a health regeneration potion. When the potion is collected by the player their health will improve allowing them to continue with the game. The crate and potions will be design to fit the overarching theme of the game environment. This contributes to a more enjoyable experience as the player can attempt to avoid death. This feature could be further expanded to include a player 'level up' which can improve aspects such as their speed, health damage, etc.

### Dependencies
This feature relies on previously implemented health mechanics, a health value and the ability to inflict change to health, take damage or heal. 

### Milestones
- [x] #98
- [x] #99
- [x] #100
- [x] #101 - (integrated into the barrel)
- [x] #102
- [x] #103
- [x] #104

**Completion Deadline:** Sep 14th

### Extras
- [ ] Player level up 
- [ ] Have player attack damage increase when potion collected

### Documentation
[Design Wiki](https://github.com/UQdeco2800/2021-studio-2/wiki/Design-Document)

### Members 
Krista Bradshaw (@krista-b) (@krista-b#4224)
Nichola Hettige (@nichola-hettige) (@Nichola H#8255)
Rodger Xiang (@r-xian) (@GGGGGGGGG#4624)
Sadra Bayat Tork (@sadrabt) (@Sadra#9931)
Sean Di Mario (@SeanDiMario) (@SeanDM#9980)
