### ISSUE TITLE
<Task> Basic Movement and Mobility

### ISSUE THREAD

**Issue by GreyAtlantean** [UQdeco2800/2021-studio-2#9]
Task from #4 

## Basic Movement

Implement basic movement and collision for the player character and try to test the movement and refine it so it feels fluid. The movement and control of the character will be a defining part of the game so this needs to feel very satisfying to play with. The movement of the character can feel lethargic while too slow and out of place so testing until an ideal speed is required.

The speed of the character needs to be relative to the size of the map and character as well as the movements of other entities such as enemies and bosses. 

### Milestones

- [x] Have player character respond to input
- [x] Have player character able to move in 

## Mobility

- [x] Implement a dashing ability
- [x] Test different speeds and durations the dash can last for
- [x] Add a sprinting mechanic 

### Extras

- [ ] Implement attacks that can combo with the dash ability

## Documentation
[Player Input and Controls](Player-Input-and-Controls)

### Members
- Jonathan Tang (@Jonoym)(#Jonoym#0974)
- Muhammad Pathan (@GreyAtlantean)(Grey Atlantean # 0010)

**Comment by Jonoym** [comment]
Could not implement attacks with dash as it was dependent on weapons team.
