### ISSUE TITLE
<Task> Cutscene Character Movement

### ISSUE THREAD

**Issue by Jonoym** [UQdeco2800/2021-studio-2#93]
This ticket is a part of Feature #84, Dialogue and Cutscenes extension

# Cut scenes

Cutscenes should be used to guide the player, this could be in providing help, knowledge or general storyline. 

## Tasks

- [x] Make the character move once triggering a cutscene entity (4th August)
- [x] Combine movement of the character with text boxes appearing
- [ ] Quitting out of the cutscene will move the player instantly.

### Dependencies
Cut scenes will implement text boxes and will be triggered by bosses as well as areas in the map.

**Completion Deadline:**  September 7th .
 
# **Documentation**
[Cutscenes](Cutscenes)

# **Members**
- Jonathan Tang (@Jonoym)(Jonoym#0974)

**Comment by Jonoym** [comment]
It has been decided that allowing the player to instantly finish the cutscene movement aspect will be difficult to implement and will not look good with how the camera is currently implement due to large amounts of stuttering during the transition. The player will still be able to quit out of any dialogue that is being displayed.
