### ISSUE TITLE
[Feature] Team 2 - Minion combat and Boss fights

### ISSUE THREAD

**Issue by eco9898** [UQdeco2800/2021-studio-2#96]
# Description 
This sprint we are focusing on redoing our animations. We are also adding in new arrow types and the Boss enemy. Collision detection will be modified to track when the hitboxes are overlayed when they glitch into each other. We also have to modify the zigzag code as it is a bit fast and doesn't scale the given movement speed passed to it. Boss fights will also trigger a soundtrack change.

#  Milestones 
## Design and animations: 
- [x] #119
- [ ] #125
- [ ] Enemy sprites for sniper elves
- [x] #127
- [x] #120
- [x] #128
- [ ] #126
- [ ] Remove hitbox over the bow as this shouldn't trigger damage

## Placement:
- [x] #143
- [x] #129

## Movement
- [x] #124
- [x] #121

## Combat
- [ ] #123

## Attacks
- [x] #122

## Collision
- [x] #142
- [x] #117

## Stretch Goals: 
- [ ] Particle effect for fireballs
- [ ] Add new Boss attacks
  - [ ] Boss explosion knockback attack
  - [ ] New AI system at low health to make boss more rabid/raged
- [ ] Boss music when player approaches boss
- [ ] External melee weapon sprite like the player has

## Tasks added mid sprint
- [x] #138 
- [x] #139 
- [x] #147 
- [x] #148 
- [x] #149 
- [ ] #156 

# Members
- Fleur Nicholson (@FleurN21) Fleur#0608
- Minh Tieu (@MTbir) Minh#7523
- Eli Cox (@eco9898) .♡.𝓮𝓵𝓲.♡.#5723
- Kai Barry (@BobJohnsom) BOBJohnson#5476
- Haopeng Xia (@HaoPengXia) HaoPengXia(Barney)#8321
